### ISSUE TITLE
Video hardware not found

### ISSUE THREAD

**Issue by noisedsn** [flathub/com.viber.Viber#88]
Hi. I'm using ubuntu 23.10 and  com.viber.Viber 21.8.0.11. Other apps (including flatpak ones) are able to see my laptop's integrated camera.

Terminal output:

`$ flatpak -v run com.viber.Viber 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.viber.Viber/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/23.08/329ad0f04e21dc3234accff013641299e13a9eb2f1b2908129692b4755393789/files/lib32 does not exist
F: Cleaning up unused container id 3606993160
F: Cleaning up per-app-ID state for com.viber.Viber
F: Allocated instance id 1781795970
F: Add defaults in dir /com/viber/Viber/
F: Add locks in dir /com/viber/Viber/
F: Allowing wayland access
F: Allowing x11 access
F: Allowing pulseaudio access
F: Running 'bwrap --args 42 xdg-dbus-proxy --args=44'
F: Running 'bwrap --args 42 viber'
qt.qml.typeregistration: Invalid QML element name "ViberAdsItem"; value type names should begin with a lowercase letter
Gtk-Message: 13:06:17.557: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:06:17.558: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
sh: рядок 1: xdg-mime: команду не знайдено
could not load multimedia backend "ffmpeg"
QtMultimedia is not currently supported on this platform or compiler.
Failed to initialize QMediaPlayer "Not available"
Failed to initialize QMediaCaptureSession "Not available"
Failed to initialize QMediaRecorder "Not available"
qml: DPR: updating dpr 1.5
qml: CALL_WEB_VIEW_DEBUG: callWebEngineLoader active: false
qml: ADS: false activeAd 0
qml: Current screen: eDP-1 [w=1280, h=720, daw=1280, dah=693, dpr=1.5]
qml: incomingCallWindow active: false
qml: notificationsWindow active: false
qml: DPR: setting dpr 1.5
qml: Geometry: mh=112, mw=757, h=112, w=757, sah=693, saw=1280
qml: Position: x=262, y=531
qml: 0: qrc:///CommonWeb/vision_wasm_internal.js Ln: 3865 -> I0226 11:06:26.945000 1866800 gl_context.cc:361] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium))), renderer: WebKit WebGL
qml: 1: qrc:///CommonWeb/vision_wasm_internal.js Ln: 490 -> W0226 11:06:26.946000 1866800 gl_context.cc:1004] OpenGL error checking is disabled
qml: 0: qrc:///CommonWeb/vision_wasm_internal.js Ln: 921 -> Graph successfully started running.
qml: 2: qrc:///SettingsCameraPreview.html Ln: 38 -> Uncaught (in promise) TypeError: Failed to execute 'getUserMedia' on 'MediaDevices': At least one of audio and video must be requested
`

**Comment by AstroDot** [comment]
Hello,
Have similar problem on Linux Mint 19.3 and com.viber.Viber 21.8.0.11.

**Comment by noisedsn** [comment]
> Hello, Have similar problem on Linux Mint 19.3 and com.viber.Viber 21.8.0.11.

This appears to be a Viber problem itself. Deb version is affected also.

**Comment by AstroDot** [comment]
> > Hello, Have similar problem on Linux Mint 19.3 and com.viber.Viber 21.8.0.11.
> 
> This appears to be a Viber problem itself. Deb version is affected also.

Camera is also not shown.

**Comment by wooque** [comment]
I had same problem with deb version on Debian. Viber depends on **libavfromat58**, **libswscale5** and other libraries that are dependencies of those 2, which are not explicitly stated as dependencies. They are not available in Debian 12, but Debian 11, so I installed them with all dependent libraries from Debian 11. On Ubuntu they are available in 22.04, so for newer Ubuntu versions you have to pull those libraries from 22.04 repos. Flatpak on the other hand should try to include those libraries in the package, because that is the point of it.

**Comment by karkusviktor** [comment]
Thanks for the tip. I looked around in the flathub repos and found this issue: https://github.com/flathub/com.parsecgaming.parsec/issues/23
I tested and downgrading runtime to 21.08 indeed fixed the issue for me.

**Comment by sophom** [comment]
Thank you. Thank you. I can confirm that your PR does get my camera working again. I'm on Mint (based on 22.04)

**Comment by noisedsn** [comment]
Can't load uri https://dl.flathub.org/build-repo/90175/com.viber.Viber.flatpakref: Server returned status 404

Was it just temporary link?

**Comment by karkusviktor** [comment]
Yes, AFAIK stuff in the test repo where flathubbot deploys are quite short lived.
I don't know the exact retention policy.

**Comment by gogi983** [comment]
> Thanks for the tip about the libraries. I looked around in the flathub repos and found this issue: [flathub/com.parsecgaming.parsec#23](https://github.com/flathub/com.parsecgaming.parsec/issues/23) I tested and downgrading the runtime for Viber to 21.08 indeed fixed the issue for me. I don't know if it's a good idea having separate versions for base (Electron) and runtime, hence I downgraded both in my PR.

Hi everyone,

I an experiencing the same issue, and my research on the internet led me here to this topic, but the solution quoted above that you mentionned infortunately didn´t work for me.

Here is the ouput from CLI : 

```
gogi@fedora:~$ flatpak remote-info --log flathub com.viber.Viber
Remote ‘flathub’ found in multiple installations:

   1) system
   2) user

Which do you want to use (0 to abort)? [0-2]: 1

Viber - Send free messages and make free calls

        ID: com.viber.Viber
       Ref: app/com.viber.Viber/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 21.8.0.11
   License: LicenseRef-proprietary
Collection: org.flathub.Stable
  Download: 5,0 Mo
 Installed: 13,1 Mo
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 113c328ed398e2f11a58f43b56ad188247abad5853390d2038f39c41b63c043b
    Parent: a62ea6059b01f4002de90d409d338e4227ab722e70fc136b2948fc68690087da
   Subject: Download krb5 sources from a not-broken server (171253e4)
      Date: 2024-02-19 18:32:22 +0000
   History: 

    Commit: a62ea6059b01f4002de90d409d338e4227ab722e70fc136b2948fc68690087da
   Subject: Fix: Detect Viber calls as user activity (86ec4901)
      Date: 2023-10-30 06:44:36 +0000

    Commit: bdd7587f7887db3820e7ad0ed6c31f57d954b41f94087fb31cd64dca80fa53c7
   Subject: Remove org.freedesktop.Notifications bus access (465b0ba3)
      Date: 2023-10-10 05:13:08 +0000

    Commit: 488cd06f7700364a153f52819108de63ce969b0cac8254622182be7c4b7f42e7
   Subject: Add libevent module to satisfy dependency (488cf563)
      Date: 2023-09-26 06:37:03 +0000
```
Obviously runtime and SDK are already in version 23.08, but the flatpak app still doesn´t find any video hardware.
Anybody has an idea?

Thanks.
